name: pip_services_msgdistribution
version: "1.0.0"
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This microservice is distributes messages to one or many recipients using their configured delivery methods - email or sms.
homepage: https://github.com/pip-services-users/pip-services-msgdistribution-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.0.9
  pip_services3_components: ^1.0.6
  pip_services3_container: ">=1.0.3 <2.0.0"
  pip_services3_rpc: ^1.0.3
  pip_services3_data: ^1.0.5
  pip_services3_mongodb: ^1.0.4
  http: "^0.12.0"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'